"""Shared constant values. Kept in one place so the bot and the dashboard agree."""

# Server types
MAIN = "MAIN"
DESTINATION = "DESTINATION"
MAIN_TYPES = (MAIN, DESTINATION)
SERVER_TYPE_LABELS = {MAIN: "Main (default)", DESTINATION: "Main (additional)", "FEEDER": "Feeder", "DISABLED": "Disabled"}
FEEDER = "FEEDER"
DISABLED = "DISABLED"
SERVER_TYPES = (MAIN, DESTINATION, FEEDER, DISABLED)

# Funnel modes
LIVE = "LIVE"
DRY_RUN = "DRY_RUN"
OFF = "OFF"
FUNNEL_MODES = (LIVE, DRY_RUN, OFF)

# DM policies
ONCE_PER_FEEDER = "ONCE_PER_FEEDER"
ONCE_GLOBAL = "ONCE_GLOBAL"
COOLDOWN_DAYS = "COOLDOWN_DAYS"
DM_POLICIES = (ONCE_PER_FEEDER, ONCE_GLOBAL, COOLDOWN_DAYS)

# DM event statuses
DM_SENT = "SENT"
DM_FAILED_CLOSED = "FAILED_DM_CLOSED"
DM_FAILED_OTHER = "FAILED_OTHER"
DM_SKIPPED_IN_MAIN = "SKIPPED_ALREADY_IN_MAIN"
DM_SKIPPED_POLICY = "SKIPPED_POLICY"
DM_SKIPPED_DEV = "SKIPPED_DEVELOPMENT_MODE"
DM_DRY_RUN = "DRY_RUN"
# Statuses that count as "we already tried to reach this person".
DM_ATTEMPTS = (DM_SENT, DM_FAILED_CLOSED, DM_FAILED_OTHER)

# Attribution statuses
ATTR_INVITE = "INVITE"
ATTR_UNKNOWN = "UNKNOWN"
ATTR_AMBIGUOUS = "AMBIGUOUS"

# Message kinds / scopes / statuses
KIND_DM = "DM"
KIND_PUBLIC = "PUBLIC"
MESSAGE_KINDS = (KIND_DM, KIND_PUBLIC)

SCOPE_GLOBAL = "GLOBAL"
SCOPE_FEEDER = "FEEDER"

DRAFT = "DRAFT"
PUBLISHED = "PUBLISHED"
ARCHIVED = "ARCHIVED"

# Role rule actions
ACTION_KICK = "KICK"
ACTION_ADD_ROLE = "ADD_ROLE"
ACTION_REMOVE_ROLE = "REMOVE_ROLE"
ACTION_LOG_ONLY = "LOG_ONLY"
ROLE_ACTIONS = (ACTION_KICK, ACTION_ADD_ROLE, ACTION_REMOVE_ROLE, ACTION_LOG_ONLY)

# Task queue types (dashboard -> bot)
TASK_TEST_DM = "TEST_DM"
TASK_REPAIR = "REPAIR"
TASK_SYNC_PUBLIC = "SYNC_PUBLIC"
TASK_SETUP_FEEDER = "SETUP_FEEDER"
TASK_ROTATE_INVITE = "ROTATE_INVITE"
TASK_FRESH_SETUP = "FRESH_SETUP"

# Button modes. Discord only allows a custom colour on an interactive button;
# a button that carries a URL is always its fixed Link style.
BUTTON_LINK = "LINK"
BUTTON_INTERACTIVE = "INTERACTIVE"
BUTTON_MODES = (BUTTON_LINK, BUTTON_INTERACTIVE)

BUTTON_STYLES = ("PRIMARY", "SECONDARY", "SUCCESS", "DANGER")

TASK_PENDING = "PENDING"
TASK_RUNNING = "RUNNING"
TASK_DONE = "DONE"
TASK_FAILED = "FAILED"
# Rows written before FAILED existed use ERROR; treated as the same thing.
TASK_ERROR = "ERROR"
TASK_FAILED_STATES = (TASK_FAILED, TASK_ERROR)
TASK_FINISHED_STATES = (TASK_DONE, TASK_FAILED, TASK_ERROR)
TASK_MAX_ATTEMPTS = 3
